pear upgrade pear
pear install   mdb2
pear install   mdb2_driver_pgsql
pear install  Config
pear install  Auth
pear install  HTTP_Request
pear install  HTTP_Client
pear install  HTTP_Download
pear install  MIME_Type
pear install  HTTP
pear install  HTTP_Header
pear install  HTTP_Upload
pear install  File
pear install  System_Command
pear install  Net_SMTP
pear install  Mail
pear install  Mail_Mime
pear install  Net_IPv4
pear install  Net_IMAP
pear install  Net_POP3
pear install  Net_Cyrus-0.3.1
pear install  Net_Server
pear install  Net_URL
pear install  XML_Parser
pear install  XML_RPC
pear install  XML_Util
pear install  PHP_Compat
pear install  Image_Barcode
pear channel-update pear.php.net
