make -C /usr/ports/archivers/php5-bz2 package-recursive
make -C /usr/ports/archivers/php5-zlib package-recursive
make -C /usr/ports/databases/php5-pgsql package-recursive
make -C /usr/ports/devel/php5-pcntl package-recursive
make -C /usr/ports/devel/php5-pcre package-recursive
make -C /usr/ports/security/php5-mcrypt package-recursive
make -C /usr/ports/security/php5-mhash package-recursive
make -C /usr/ports/sysutils/php5-posix package-recursive
make -C /usr/ports/textproc/php5-xml package-recursive
make -C /usr/ports/www/php5-session package-recursive
